os: linux
dist: bionic
sudo: true
language: java
jdk: openjdk11

addons:
  apt:
    packages:
      - libstdc++6
      - build-essential
      - g++

script:
  - bin/setup-linux

env:
  global:
    - BUNDLE_PATH=vendor/bundle
    - PATH="~/.rbenv/bin:~/.rbenv/shims:/usr/local/bin:/usr/bin:/bin:/sbin:/usr/sbin:/opt/local/bin"
    - BAZEL_OPTS="--host_jvm_args=-Xmx500m --host_jvm_args=-Xms500m"
    - BAZEL_BUILD_OPTS="--curses=no --verbose_failures -j 20 --show_progress_rate_limit 0 "
    - BAZEL_TEST_OPTS="--verbose_failures --test_output=streamed --test_verbose_timeout_warnings "
